export { AcceptFriendRequestSwagger } from './acceptFriendRequest'
export { addFriendSwagger } from './addFriend'
export { loginSwagger } from './login'
export { registerSwagger } from './register'
export { getAllSwager } from './getAll'
export { getAllExceptMyfriendSwagger } from './getAllExcpetMyFriend'
export { getfriendSwagger } from './getFriend'
export { getMeSwagger } from './getMe'